// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDshhkMpWaGX2TLR5QdsEyUQizrrobRmNo',
    appId: '1:1035101659237:web:74d1d5102d5fa7f337e68c',
    messagingSenderId: '1035101659237',
    projectId: 'nft-08-3fbb3',
    authDomain: 'nft-08-3fbb3.firebaseapp.com',
    storageBucket: 'nft-08-3fbb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3l1EZytAOUxno02yebt0fDZPHPhZ92n0',
    appId: '1:1035101659237:android:c4de1438d0a4bb5d37e68c',
    messagingSenderId: '1035101659237',
    projectId: 'nft-08-3fbb3',
    storageBucket: 'nft-08-3fbb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-u5bPyUdfCUftvdchc5liTTeGhcMWt8',
    appId: '1:1035101659237:ios:8762584b3a0b586837e68c',
    messagingSenderId: '1035101659237',
    projectId: 'nft-08-3fbb3',
    storageBucket: 'nft-08-3fbb3.appspot.com',
    iosClientId: '1035101659237-5htcirpthclhm376affvqi9tmjbhd7ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-u5bPyUdfCUftvdchc5liTTeGhcMWt8',
    appId: '1:1035101659237:ios:8762584b3a0b586837e68c',
    messagingSenderId: '1035101659237',
    projectId: 'nft-08-3fbb3',
    storageBucket: 'nft-08-3fbb3.appspot.com',
    iosClientId: '1035101659237-5htcirpthclhm376affvqi9tmjbhd7ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatSystem',
  );
}
